In [2]:
import numpy as np

In [4]:
a = np.array(1)
a

array(1)

In [6]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [8]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [9]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)

['1' '2.0' '3']


In [11]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [13]:
print(np.array(1+2j).dtype)
print(np.array(print).dtype)

complex128
object


##### dtype 속성을 사용하여 자료형 지정

In [15]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

int8


In [17]:
dtype2 = np.array([1,2,3], dtype=float)
print(dtype2.dtype)

float64


In [18]:
dtype3 = np.array([1,2,3], dtype=str)
print(dtype3.dtype)

<U1


In [21]:
dtype4 = np.array([1,2.1,'3'], dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


In [22]:
# 오류나는거 맞음 'data'는 못바꾼다
dtype5 = np.array([1,'data',print], dtype=float)
print(dtype5.dtype)

ValueError: could not convert string to float: 'data'

In [25]:
# 배열크기 확인
print(ndarr_1.shape)

(3,)


In [26]:
# 배열차원 확인
print(ndarr_1.ndim)

1


#### N차원 배열
- Scalar: 숫자
- Vector: scalar의 배열, 1차원 배열
- Matrix: vector의 배열, 2차원 배열
- Tensor: matrix의 배열, 3차원 배열이상

In [27]:
# 1차원 배열 생성
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


In [29]:
# 2차원 배열 생성
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [30]:
# 3차원 배열 생성
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


#### 배열의 정보확인

In [31]:
# 배열 요소의 개수 확인
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [39]:
# 연습문제
d = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(d)
print(d.ndim)
print(d.size)
print(d.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
2
9
(3, 3)


#### 자료형 변환(리스트)

In [45]:
# 리스트에서 ndarray 변환
list1 = [1,2,3]
arr1 = np.array(list1)
print(arr1, type(arr1))

[1 2 3] <class 'numpy.ndarray'>


In [46]:
# ndarray에서 리스트로 변환
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2, type(list2))

[1, 2, 3] <class 'list'>


In [47]:
# 2차원 리스트 변환
list3 = [[1,2,3],[4,5,6]]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [50]:
# 주의해야할 점 - list의 shape 다른 경우
list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)
print(arr4.size, arr4.shape, arr4.ndim)

[list([1, 2, 3, 4]) list([5, 6, 7])]
2 (2,) 1


C:\Users\admin\AppData\Local\Temp\ipykernel_3024\2166626075.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


#### 자료형 변환(튜플) - 리스트와 동일

In [52]:
# 튜플 -> ndarray 변환
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


In [53]:
# ndarray -> 튜플 변환
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

(1, 2, 3)


#### 자료형 변환(세트, 딕셔너리)

In [57]:
# 세트변환
set1 = {1,2,3}
arr = np.array(set1)
print(arr, arr.size, arr.shape)

{1, 2, 3} 1 ()


In [56]:
print(arr.size)

1


In [59]:
# 딕셔너리 변환
dict1 = {'a':1, 'b':2, 'c':3}
arr = np.array(dict1)
print(arr)

{'a': 1, 'b': 2, 'c': 3}


In [60]:
print(arr.size)

1


#### 배열 인덱싱

In [62]:
# 리스트 인덱싱과 유사
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]
 #1 가져오기
print(list_[0][0][0])
 #4 가져오기
print(list_[0][1][1])
 #7 가져오기
print(list_[1][1][0])

1
4
7


In [64]:
# arr
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
 #1 가져오기
print(arr_[0][0][0])
 #4 가져오기
print(arr_[0][1][1])
 #7 가져오기
print(arr_[1][1][0])

1
4
7


In [66]:
# ndarray의 인덱싱
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
 #1 가져오기
print(arr_[0,0,0])
 #4 가져오기
print(arr_[0,1,1])
 #7 가져오기
print(arr_[1,1,0])

1
4
7


In [68]:
# ndarray의 인덱싱
arr_1 = np.array([[1,2],[3,4],[5,6]])
 # 0행 가져와 2차원 배열 만들기
print(arr_1[[0]])  
 # 0,2행 가져와 2차원 배열 만들기
print(arr_1[[0,2]])  ## print(arr_1[[0],:])
 # 다음 결과는?
print(arr_1[[0,1,2],[0,1,0]])   # row1, col1=0,0 | row2, col2 =1,1 | row3, col3=2,0
 # 같은 위치 데이터 여러번 사용가능
print(arr_1[[0,0],[1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [70]:
# 배열 인덱싱
arr_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])
# 두개의 1차원배열만들기
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])
# 다음 코드의 실행 결과는?
print(arr_2[b,c]) 

[ 1  6  7 11]


In [74]:
# Boolean 인덱싱
#기본데이터
arr = np.array([1,2,3,4,5])

array([3])

In [72]:
# True, False
print(arr[[True,False,True,True,False]])

[1 3 4]


In [73]:
print(arr[arr >= 3])

[3 4 5]


In [82]:
# 배열 인덱싱 문제
score = np.array([[78,91,84,89,93,65],[82,87,96,79,91,73]])

print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])


[91 93]
[96 91]


###### 2022-05-25

#### 배열 슬라이싱
 > ndarray의 슬라이싱
  - 행과 열 부분을 나눠서 슬라이싱 가능
  - 다차원 배열의 부분 데이터를 추출할 때유용

In [14]:
# 기본 데이터 4 x 5 형태의 2차원배열
matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20]])

matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
# 0열 전체 슬라이싱
print(matrix[:,0], '\n')
# 0열 전체 슬라이싱 (2차원 유지)
print(matrix[:,:1])

[ 1  6 11 16] 

[[ 1]
 [ 6]
 [11]
 [16]]


In [9]:
# 1행 전체 슬라이싱
print(matrix[1,:])
# 1행 전체 슬라이싱
print(matrix[1])  # rank > row > col 순으로 :(콜론) 생략 가능
# 1행 전체 슬라이싱(2차원 유지)
print(matrix[1:2,:])  # or print(matrix[[1]])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [19]:
# 3~4열 전체 슬라이싱
print(matrix[:,3:], '\n')
# 0행, 1~3열 슬라이싱
print(matrix[0,1:-1])     # == [0, 1:4]

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]] 

[2 3 4]


#### 배열 인덱싱, 슬라이싱 복합

In [20]:
# 2~3행, 2~4열 슬라이싱
print(matrix[-2:,-3:])
# 1~2행, 1~2열 슬라이싱
print(matrix[1:-1,1:3])

[[13 14 15]
 [18 19 20]]
[[ 7  8]
 [12 13]]


In [23]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
# 1, 3행, 2~4열 슬라이싱
print(matrix[[1,3],2:])
# 1~2행, 1,3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


In [49]:
# 문제3 # 10,2,6 추출
tensor = np.array([[[1,2,3],
                    [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])

print(tensor[[1,0,0],[1,0,1],[0,1,2]])

[10  2  6]


In [57]:
# 문제4 # [[1 2][4 5]] 배열과 [9 12]배열 추출
print(tensor[0, :, :2])
print(tensor[1, :, 2])

[[1 2]
 [4 5]]
[ 9 12]
