#### Reshape
 - 배열의 shape을 변형해주는 함수
 - 배열의 요소 개수를 유지하며 형태만 변경
 - 변형 전 size와 변형 후 size가 동일해야 함

In [363]:
import numpy as np

In [364]:
# array.reshape(size)
arr = np.array([[1,2,3],[4,5,6]])  # 2X3 형태의 2차원 배열
print(arr.reshape(3,2))  # 3X2 형태의 배열로 변형

[[1 2]
 [3 4]
 [5 6]]


In [365]:
# 6x1 배열로
print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [366]:
# 1x6 배열로
print(arr.reshape(1,6))

[[1 2 3 4 5 6]]


In [367]:
# 3x1x2 배열로 변형
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [368]:
# ?x2배열로 변형
print(arr.reshape(-1,2))
# 2x?배열로 변형
print(arr.reshape(2,-1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [369]:
# 차원 줄이고싶으면 ,(컴마) 줄이면 됨
# 반대로 늘리고 싶으면 , 늘리기
print(arr.reshape(6))

[1 2 3 4 5 6]


In [370]:
# 문제1 # 배열 만들고 (3,3,4) 형태의 3차원배열
tensor = np.array(range(1,37))
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [371]:
# 문제 2 # tensor 배열을 2차원 배열로 변형, 열의개수는 9
tensor.reshape(-1,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

#### Flatten
 - 다차원 배열을 1차원 배열로 변형

In [372]:
# 문제3번 tensor를 바꾼거
print(tensor.reshape(3,3,4).flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [373]:
# shape(2,3) -> shape(6,)
print(arr.flatten())
# shape(1,6) -> shape(6,)
print(arr.reshape(1,6).flatten())
# shape(3,1,2) -> shape(6,)
print(arr.reshape(3,1,2).flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


#### Arange 
 - range 함수와 비슷한 기능
 - 값의 범위를 지정하여 값이 채워져 있는 배열을 생성
 - 특정한 규칙에 따라 증가하는 갑을 넣는 것도 가능

In [374]:
# np.arange(size)
print(np.arange(30))   # == np.array(range(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [375]:
# 간격 지정 : np.arange(strat, end, step)
print(np.arange(0,10,2))
print(np.arange(0,2,0.2))
print(np.arange(10,0,-1))

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[10  9  8  7  6  5  4  3  2  1]


#### Arange + Reshape
 - 배열 요소를 순서대로 가지는 다차원 배열 생성 가능

In [376]:
# arange + reshape
print(np.arange(1,26).reshape(5,5),'\n')
print(np.arange(0,6,0.2).reshape(3,2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


In [377]:
# 문제3 # 100~190까지 10간격의 배 열생성, (2,5)형태의 2차원 배열
print(np.arange(100,200,10).reshape(2,5),'\n')

# 문제4 # -2부터 2까지 0.5간격의 배열 생성, 2차원배열 변형
print(np.arange(-2, 2.1, 0.5).reshape(3,3), '\n')

# 문제4.1 # -2부터 2까지 0.5간격의 배열 생성, 3차원배열 변형
print(np.arange(-2, 2.1, 0.5).reshape(1,3,3))

[[100 110 120 130 140]
 [150 160 170 180 190]] 

[[-2.  -1.5 -1. ]
 [-0.5  0.   0.5]
 [ 1.   1.5  2. ]] 

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


#### Zeros
 - 0으로 채워진 배열 생성
 - shape 지정이 가능

In [378]:
# np.zeros(shape,dtype)
print(np.zeros(shape=(5,), dtype=np.int8))

[0 0 0 0 0]


In [379]:
print(np.zeros((5), int))

[0 0 0 0 0]


In [380]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


#### Ones
 - 1으로 채워진 배열 생성
 - shape 지정이 가능

In [381]:
# np.ones(shape, dtype)
print(np.ones(shape=(5,),dtype=np.int8))

[1 1 1 1 1]


In [382]:
print(np.ones((5),int))

[1 1 1 1 1]


In [383]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


#### Empty
 - shape만 주어지고 비어있는 배열 생성
 - 배열을 생성만 하고 값을 주지않아 메모리에 저장되어 있던 기존 값이 저장될 수 있음
 - zeros랑 다르다

In [384]:
# np.empty(shape, dtype)
print(np.empty(shape=(10,),dtype=np.int32))

[100 110 120 130 140 150 160 170 180 190]


In [385]:
print(np.empty((2,5),np.int8))

[[0 1 1 1 1]
 [1 1 1 1 1]]


#### Zeros_like / Ones_like / Empty_like
 - 입력받은 배열과 같은 shape, dtype의 배열 생성

In [386]:
# np.zeros_like(ndarray)
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [387]:
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [388]:
matrix = np.arange(-2,2,0.2).reshape(2,10)
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [389]:
# np.empty_like(ndarray)
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


#### Identity
 - 단위 행렬 - 주대각선의 값이 1이고 나머지는 0인 정사각 행렬

In [390]:
# np.identity(size, dtype)
print(np.identity(5,dtype=np.str_))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


In [391]:
print(np.identity(2, dtype=np.int8))

[[1 0]
 [0 1]]


#### Eye
 - 대각선이 1로 채워지는 행렬
 - 대각선의 시작 위치 지정 가능
 - k: 대각선의 시작 위치를 입력받은 수만큼 오른쪽으로 이동
 - M: 보여지는 열의 개수를 지정

In [392]:
# np.eye(size, M, k, dtype)
print(np.eye(5, dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [393]:
print(np.eye(5,k=2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [394]:
print(np.eye(5, M=10, k=-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


#### Full
 - 입력 값으로 채워지는 행렬

In [395]:
print(np.full((2,5), 5))

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [396]:
print(np.full((5,4),'a'))

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [397]:
np.ones((3,3)) * 3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [398]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

#### Random.randint
 - 주어진 범위 안의 랜덤한 값을 뽑는 함수

In [399]:
# np.random.randint(range)
## 0~5까지의 정수중 하나뽑기
print(np.random.randint(6))

5


In [400]:
## 1~19까지의 정수 중 하나 뽑기
print(np.random.randint(1,20))

12


In [401]:
## 1~19까지의 정수 중 두개 뽑기
print(np.random.randint(1,20,2))

[ 4 10]


#### Random.rand
 - 랜덤한 값으로 채워지는 배열
 - 표준정규분포 난수를 shape 형태의 배열로 생성
 - 0~1사이의 값을 가짐

In [402]:
# np.random.rand(shape)
print(np.random.rand(3))

[0.25239491 0.53496044 0.23959811]


In [403]:
print(np.random.rand(3,2))

[[0.87713704 0.95652661]
 [0.77244996 0.21521889]
 [0.00310066 0.326416  ]]


#### Random.randn
 - 랜덤한 값으로 채워지는 배열
 - 평균 0, 표준편차 1의 가우시안 표준정규분포 난수를 shape 형태의 배열로 생성

In [404]:
# np.random.randn(shape)
print(np.random.randn(3))

[-0.35135194 -1.20543337 -0.14754808]


In [405]:
print(np.random.randn(3,2))

[[ 2.29089648 -1.09859667]
 [ 1.166865    0.87383148]
 [-0.57340095  0.09655677]]


#### 연산함수
 - 배열의 요소값들을 이용하여 연산을 할 수 있게 해주는 함수

#### 합(Sum)
 - 요소들의 합을 구해주는 함수
 - ndarray.sum()

In [406]:
# 2차원 배열 합
matrix = np.arange(1,7).reshape(2,3)
print(matrix.sum())

21


In [407]:
print(matrix.sum(axis=0))   #행끼리 더하기(위아래)
print(matrix.sum(axis=1))   #열끼리 더하기(좌 우)

[5 7 9]
[ 6 15]


In [408]:
# 3차원 배열 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [409]:
# 3차원 배열 합
print(tensor.sum(axis=0))
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


#### 평균(mean)
 - 합과 동일

In [410]:
# 2차원 배열 평균
print(matrix.mean())         # 전체평균
print(matrix.mean(axis=0))   # 행끼리 평균(위아래)
print(matrix.mean(axis=1))   # 열끼리 평균(좌 우)

3.5
[2.5 3.5 4.5]
[2. 5.]


#### 표준 편차(std)
 - 합, 평균과 동일

In [411]:
# 2차원 배열 표준 편차
print(matrix.std())        # 전체 표준 편차
print(matrix.std(axis=0))  # 행끼리 표준 편차(위 아래)
print(matrix.std(axis=1))  # 열끼리 표준 편차(좌 우)

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


#### 그 외 수학 연산자

In [412]:
# 지수(exp)
print(np.exp(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [413]:
# 로그(log)
print(np.log(matrix))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [414]:
# 제곱근(sqrt)
print(np.sqrt(matrix))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [415]:
# 삼각함수(sin)
print(np.sin(matrix))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [416]:
# 삼각함수(cos)
print(np.cos(matrix))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [417]:
# 삼각함수(tan)
print(np.tan(matrix))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


#### 배열 정렬(Sort)

In [418]:
# 1차원 배열 정렬
## randint를 사용하여 1~100숫자 중 5개를 뽑아 배열 생성
vector = np.array([np.random.randint(1,100)
                   for n in range(5)])
print(vector)

[69 37 19 78 65]


In [419]:
## 리스트 내 for문
list_ = [1,2,3,4,5,6,7,8,9,10]
list2_ = [num * 3 for num in list_ if num % 2 == 1]
list2_

[3, 9, 15, 21, 27]

In [420]:
print(np.sort(vector))         #오름차순으로 정렬

[19 37 65 69 78]


In [421]:
print(np.sort(vector)[::-1])   #내림차순으로 정렬

[78 69 65 37 19]


In [422]:
# 2차원 배열 정렬
## randint를 사용하여 1~100숫자중20개를 뽑아 배열 생성
matrix = np.array([np.random.randint(1,100)
                   for n in range(20)]).reshape(4,5)
print(matrix)

[[22 26 95 93 33]
 [73 36 84 41  8]
 [53 97 34 30  5]
 [11 76 18 15 84]]


In [423]:
print(np.sort(matrix))     # 열 기준으로 정렬

[[22 26 33 93 95]
 [ 8 36 41 73 84]
 [ 5 30 34 53 97]
 [11 15 18 76 84]]


In [424]:
print(np.sort(matrix, axis=0))   # 행 기준으로 정렬

[[11 26 18 15  5]
 [22 36 34 30  8]
 [53 76 84 41 33]
 [73 97 95 93 84]]


#### 배열 합치기 (Vstack)
 - 2개 이상의 배열을 수직으로 합체

In [425]:
# np.vstack([arr1, arr2])
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


In [426]:
# np.hstack([arr1, arr2])
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.hstack([vector1, vector2]))

[[1 4]
 [2 5]
 [3 6]]


#### 배열 합치기(Concatenate)
 - 2개 이상의 배열을 수직, 수평으로 합체

In [427]:
# np.concatenate(arr1, arr2, axis)
## 1차원은 수직으로 결합 X
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.concatenate([vector1, vector2], axis=0))

[1 2 3 4 5 6]


In [428]:
####
matrix1 = np.array([1,2,3]).reshape(3,1)
matrix2 = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([matrix1, matrix2], axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [429]:
# np.concatenate(arr1, arr2, axis)
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([vector1, vector2], axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [430]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([matrix1, vector2], axis=1))

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [433]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1, matrix2], axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [434]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1, matrix2], axis=1))

[[1 2 5 6]
 [3 4 7 8]]


#### 행/열 바꾸기(transpose)
 - 행과 열을 뒤집어 주는 함수

In [435]:
# ndarray.tranpose()
# ndarray.T
matrix3 = np.array([[5,6]])
print(matrix3)

[[5 6]]


In [438]:
print(matrix3.shape, matrix3.transpose().shape)
print(matrix3.T)

(1, 2) (2, 1)
[[5]
 [6]]


#### Transpose + Concatenate
 - 형태를 바꿔 서로 결합할 수 없는 배열을 합칠 수 있다.

In [439]:
print(np.concatenate([matrix1, matrix3]))

[[1 2]
 [3 4]
 [5 6]]


In [440]:
# 오류나는거맞음
print(np.concatenate([matrix1, matrix3], axis=1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [441]:
print(np.concatenate([matrix1, matrix3.T],axis=1))

[[1 2 5]
 [3 4 6]]


#### 인덱스 반환 함수
 - 최대값, 최소값의 인덱스
 - argmax, argmin

In [442]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [443]:
print(np.argmax(a), np.argmin(a))

9 0


In [444]:
print(np.argmax(a, axis=0))

[1 1 1 1 1]


In [445]:
#
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]


In [448]:
print(np.argmin(b, axis=1))

[0 3 2]


In [449]:
print(np.argmin(b, axis=0))

[0 0 2 1]


#### 배열 인덱싱(Fancy Index)
 - 인덱스의 값을 가지는 배열을 통해 인덱싱

In [450]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [451]:
print(a[b])

[4 5 6 7]


In [452]:
# 인덱스 반환 함수 + fancy index
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
9


In [453]:
print(a[b])

19
