#### 산술연산
 - 배열은 기본적으로 요소의 연산이 가능
 - shape이 같은 배열은 연산 가능

In [3]:
import numpy as np

In [1]:
# 리스트의 덧셈
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [5]:
# 배열의 덧셈
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


In [6]:
# 모양이 같은 배열 연산
arr1 = np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype=np.int32).reshape(2,3)
print(arr1 + arr2)  #더하기

[[12. 14. 16.]
 [18. 20. 22.]]


In [7]:
print(arr2-arr1)  #빼기

[[10. 10. 10.]
 [10. 10. 10.]]


In [8]:
print(arr1 * arr2)   #곱하기

[[11. 24. 39.]
 [56. 75. 96.]]


In [9]:
print(arr2/arr1)  #나누기

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]


In [10]:
print(arr1 ** arr2)  #제곱

[[1.00000000e+00 4.09600000e+03 1.59432300e+06]
 [2.68435456e+08 3.05175781e+10 2.82110991e+12]]


In [11]:
print(arr2 // arr1)  #몫

[[11.  6.  4.]
 [ 3.  3.  2.]]


In [12]:
print(arr2 % arr1)  #나머지

[[0. 0. 1.]
 [2. 0. 4.]]


In [13]:
#  Numpy의 연산 함수
## np.add(arr1, arr2)

print(arr1 + arr2)

[[12. 14. 16.]
 [18. 20. 22.]]


In [14]:
print(np.add(arr1,arr2))

[[12. 14. 16.]
 [18. 20. 22.]]


In [15]:
## np.substract(arr1, arr2)
print(arr1 - arr2)

[[-10. -10. -10.]
 [-10. -10. -10.]]


In [16]:
print(np.subtract(arr1, arr2))

[[-10. -10. -10.]
 [-10. -10. -10.]]


In [17]:
## np. multiply(arr1, arr2)
print(arr1 * arr2)

[[11. 24. 39.]
 [56. 75. 96.]]


In [18]:
print(np.multiply(arr1,arr2))

[[11. 24. 39.]
 [56. 75. 96.]]


In [19]:
## np.divdie(arr1, arr2)
print(arr1/arr2)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


In [20]:
print(np.divide(arr1, arr2))

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


In [23]:
# Broadcasting
# 연산하고자 하는 배열의 모양이 다른 경우의 연산

## 일반적인 상황 (요류나는거맞음)
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3+arr4)

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [24]:
# Broadcasting : shape이 다른 배열 간 연산 지원
## 배열과 스칼라의 연산
scalar = 10
vector = np.array([1,2,3])
print(scalar + vector)

[11 12 13]


In [25]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,3]])
print(scalar + matrix)

[[11 12 13]
 [14 15 13]]


In [26]:
scalar = 10
tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])
print(scalar + tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


In [27]:
# 벡터와 매트릭스의 연산
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix+vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [28]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)
print(matrix+vector)

[[12 13 14]
 [16 17 18]
 [20 21 22]]


In [29]:
# 벡터와 벡터의 브로드캐스팅 연산
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]


In [30]:
print(arr1 + arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [31]:
np.broadcast(arr1, arr2)

In [32]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

In [33]:
np.broadcast(arr3, arr4)

#### 행렬 연산
 - 수학에서의 행렬의 곱셈

In [34]:
# np.dot(arr1, arr2) 함수 사용
## 일반적인 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

[1 4 9]


In [35]:
## np.dot 사용 행렬곱
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T
print(np.dot(arr1, arr2))

14


In [36]:
## arr1.dot(arr2)
print(arr1.dot(arr2))

14


In [37]:
## arr1@arr2
print(arr1@arr2)

14


 - 2차원 배열 행렬곱

In [38]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
